// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://neondb_owner:npg_npg_rS4vk3iIOlFa@ep-polished-dream-azeu5ljm.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
  },
});
